"""add_ai_usage_logs_table

Revision ID: 88945633fb7e
Revises: 34595774c5f5
Create Date: 2025-12-19 16:51:34.176381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88945633fb7e'
down_revision: Union[str, None] = '34595774c5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['project_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_ai_usage_logs_case_id', 'ai_usage_logs', ['case_id'], unique=False)
    op.create_index('ix_ai_usage_logs_project_id', 'ai_usage_logs', ['project_id'], unique=False)
    op.create_index('ix_ai_usage_logs_provider', 'ai_usage_logs', ['provider'], unique=False)
    op.create_index('ix_ai_usage_logs_requested_at', 'ai_usage_logs', ['requested_at'], unique=False)
    op.create_index('ix_ai_usage_logs_session_id', 'ai_usage_logs', ['session_id'], unique=False)
    op.create_index('ix_ai_usage_logs_success', 'ai_usage_logs', ['success'], unique=False)
    op.create_index('ix_ai_usage_logs_task_type', 'ai_usage_logs', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_usage_logs_task_type', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_success', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_session_id', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_requested_at', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_provider', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_project_id', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_case_id', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
