"""Initial tables

Revision ID: 52dd49119a74
Revises: 
Create Date: 2025-12-16 13:35:51.212189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52dd49119a74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analysis_type', sa.String(length=30), nullable=True),
    sa.Column('files_count', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=200), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('current_step_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_analysis_sessions_created_at', 'analysis_sessions', ['created_at'], unique=False)
    op.create_index('ix_analysis_sessions_session_id', 'analysis_sessions', ['session_id'], unique=False)
    op.create_index('ix_analysis_sessions_status', 'analysis_sessions', ['status'], unique=False)
    op.create_index('ix_analysis_sessions_user_id', 'analysis_sessions', ['user_id'], unique=False)
    op.create_table('bank_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_bank_statements_bank_name', 'bank_statements', ['bank_name'], unique=False)
    op.create_index('ix_bank_statements_uploaded_at', 'bank_statements', ['uploaded_at'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('contract_title', sa.String(length=500), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('contract_value', sa.String(length=200), nullable=True),
    sa.Column('deposit_amount', sa.String(length=200), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('tenant', sa.String(length=500), nullable=True),
    sa.Column('customer_name', sa.String(length=500), nullable=True),
    sa.Column('unit_for_lease', sa.String(length=200), nullable=True),
    sa.Column('gla_for_lease', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gfa', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('handover_date', sa.Date(), nullable=True),
    sa.Column('service_charge_rate', sa.String(length=200), nullable=True),
    sa.Column('service_charge_applies_to', sa.String(length=200), nullable=True),
    sa.Column('governing_law', sa.String(length=200), nullable=True),
    sa.Column('termination_clauses', sa.Text(), nullable=True),
    sa.Column('signatures_present', sa.Boolean(), nullable=False),
    sa.Column('key_obligations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('special_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_contracts_contract_number', 'contracts', ['contract_number'], unique=False)
    op.create_index('ix_contracts_customer_name', 'contracts', ['customer_name'], unique=False)
    op.create_index('ix_contracts_effective_date', 'contracts', ['effective_date'], unique=False)
    op.create_index('ix_contracts_tenant', 'contracts', ['tenant'], unique=False)
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('security_scan_passed', sa.Boolean(), nullable=False),
    sa.Column('estimated_sheets', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_file_uploads_file_type', 'file_uploads', ['file_type'], unique=False)
    op.create_index('ix_file_uploads_filename', 'file_uploads', ['filename'], unique=False)
    op.create_index('ix_file_uploads_is_deleted', 'file_uploads', ['is_deleted'], unique=False)
    op.create_index('ix_file_uploads_processing_status', 'file_uploads', ['processing_status'], unique=False)
    op.create_index('ix_file_uploads_session_id', 'file_uploads', ['session_id'], unique=False)
    op.create_index('ix_file_uploads_upload_timestamp', 'file_uploads', ['upload_timestamp'], unique=False)
    op.create_table('gla_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('total_gla_sqm', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_gla_projects_period_date', 'gla_projects', ['period_date'], unique=False)
    op.create_index('ix_gla_projects_product_type', 'gla_projects', ['product_type'], unique=False)
    op.create_index('ix_gla_projects_project_code', 'gla_projects', ['project_code'], unique=False)
    op.create_index('ix_gla_projects_region', 'gla_projects', ['region'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=30), nullable=False),
    sa.Column('subsidiary_name', sa.String(length=200), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detailed_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('configuration_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_assessment', sa.String(length=20), nullable=True),
    sa.Column('result_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('debug_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_analysis_results_analysis_type', 'analysis_results', ['analysis_type'], unique=False)
    op.create_index('ix_analysis_results_session_id', 'analysis_results', ['session_id'], unique=False)
    op.create_index('ix_analysis_results_subsidiary_name', 'analysis_results', ['subsidiary_name'], unique=False)
    op.create_table('bank_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('acc_no', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_balances_acc_no', 'bank_balances', ['acc_no'], unique=False)
    op.create_index('ix_bank_balances_statement_id', 'bank_balances', ['statement_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('acc_no', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('beneficiary_bank', sa.String(length=200), nullable=False),
    sa.Column('beneficiary_acc_no', sa.String(length=50), nullable=False),
    sa.Column('beneficiary_acc_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_transactions_acc_no', 'bank_transactions', ['acc_no'], unique=False)
    op.create_index('ix_bank_transactions_bank_name', 'bank_transactions', ['bank_name'], unique=False)
    op.create_index('ix_bank_transactions_date', 'bank_transactions', ['transaction_date'], unique=False)
    op.create_index('ix_bank_transactions_statement_id', 'bank_transactions', ['statement_id'], unique=False)
    op.create_table('contract_parties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_parties_contract_id', 'contract_parties', ['contract_id'], unique=False)
    op.create_index('ix_contract_parties_role', 'contract_parties', ['role'], unique=False)
    op.create_table('contract_rate_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('monthly_rate_per_sqm', sa.String(length=100), nullable=True),
    sa.Column('total_monthly_rate', sa.String(length=100), nullable=True),
    sa.Column('num_months', sa.String(length=20), nullable=True),
    sa.Column('foc_from', sa.String(length=50), nullable=True),
    sa.Column('foc_to', sa.String(length=50), nullable=True),
    sa.Column('foc_num_months', sa.String(length=20), nullable=True),
    sa.Column('service_charge_rate_per_sqm', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_rate_periods_contract_id', 'contract_rate_periods', ['contract_id'], unique=False)
    op.create_table('contract_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=False),
    sa.Column('gfa', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=500), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_units_contract_id', 'contract_units', ['contract_id'], unique=False)
    op.create_index('ix_contract_units_unit', 'contract_units', ['unit'], unique=False)
    op.create_table('gla_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('ufl_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('gla_for_lease', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tenant', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gla_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gla_records_period_date', 'gla_records', ['period_date'], unique=False)
    op.create_index('ix_gla_records_project_code', 'gla_records', ['project_code'], unique=False)
    op.create_index('ix_gla_records_project_id', 'gla_records', ['project_id'], unique=False)
    op.create_index('ix_gla_records_status', 'gla_records', ['status'], unique=False)
    op.create_index('ix_gla_records_tenant', 'gla_records', ['tenant'], unique=False)
    op.create_index('ix_gla_records_ufl_id', 'gla_records', ['ufl_id'], unique=False)
    op.create_table('gla_tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(length=500), nullable=False),
    sa.Column('gla_sqm', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gla_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gla_tenants_project_id', 'gla_tenants', ['project_id'], unique=False)
    op.create_index('ix_gla_tenants_tenant_name', 'gla_tenants', ['tenant_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gla_tenants_tenant_name', table_name='gla_tenants')
    op.drop_index('ix_gla_tenants_project_id', table_name='gla_tenants')
    op.drop_table('gla_tenants')
    op.drop_index('ix_gla_records_ufl_id', table_name='gla_records')
    op.drop_index('ix_gla_records_tenant', table_name='gla_records')
    op.drop_index('ix_gla_records_status', table_name='gla_records')
    op.drop_index('ix_gla_records_project_id', table_name='gla_records')
    op.drop_index('ix_gla_records_project_code', table_name='gla_records')
    op.drop_index('ix_gla_records_period_date', table_name='gla_records')
    op.drop_table('gla_records')
    op.drop_index('ix_contract_units_unit', table_name='contract_units')
    op.drop_index('ix_contract_units_contract_id', table_name='contract_units')
    op.drop_table('contract_units')
    op.drop_index('ix_contract_rate_periods_contract_id', table_name='contract_rate_periods')
    op.drop_table('contract_rate_periods')
    op.drop_index('ix_contract_parties_role', table_name='contract_parties')
    op.drop_index('ix_contract_parties_contract_id', table_name='contract_parties')
    op.drop_table('contract_parties')
    op.drop_index('ix_bank_transactions_statement_id', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_date', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_bank_name', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_acc_no', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index('ix_bank_balances_statement_id', table_name='bank_balances')
    op.drop_index('ix_bank_balances_acc_no', table_name='bank_balances')
    op.drop_table('bank_balances')
    op.drop_index('ix_analysis_results_subsidiary_name', table_name='analysis_results')
    op.drop_index('ix_analysis_results_session_id', table_name='analysis_results')
    op.drop_index('ix_analysis_results_analysis_type', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('ix_gla_projects_region', table_name='gla_projects')
    op.drop_index('ix_gla_projects_project_code', table_name='gla_projects')
    op.drop_index('ix_gla_projects_product_type', table_name='gla_projects')
    op.drop_index('ix_gla_projects_period_date', table_name='gla_projects')
    op.drop_table('gla_projects')
    op.drop_index('ix_file_uploads_upload_timestamp', table_name='file_uploads')
    op.drop_index('ix_file_uploads_session_id', table_name='file_uploads')
    op.drop_index('ix_file_uploads_processing_status', table_name='file_uploads')
    op.drop_index('ix_file_uploads_is_deleted', table_name='file_uploads')
    op.drop_index('ix_file_uploads_filename', table_name='file_uploads')
    op.drop_index('ix_file_uploads_file_type', table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index('ix_contracts_tenant', table_name='contracts')
    op.drop_index('ix_contracts_effective_date', table_name='contracts')
    op.drop_index('ix_contracts_customer_name', table_name='contracts')
    op.drop_index('ix_contracts_contract_number', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_bank_statements_uploaded_at', table_name='bank_statements')
    op.drop_index('ix_bank_statements_bank_name', table_name='bank_statements')
    op.drop_table('bank_statements')
    op.drop_index('ix_analysis_sessions_user_id', table_name='analysis_sessions')
    op.drop_index('ix_analysis_sessions_status', table_name='analysis_sessions')
    op.drop_index('ix_analysis_sessions_session_id', table_name='analysis_sessions')
    op.drop_index('ix_analysis_sessions_created_at', table_name='analysis_sessions')
    op.drop_table('analysis_sessions')
    # ### end Alembic commands ###
