"""add_session_id_to_bank_statements

Revision ID: 34595774c5f5
Revises: a1b2c3d4e5f6
Create Date: 2025-12-17 14:57:26.185039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34595774c5f5'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_statements', sa.Column('session_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_bank_statements_session_id'), 'bank_statements', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_statements_session_id'), table_name='bank_statements')
    op.drop_column('bank_statements', 'session_id')
    # ### end Alembic commands ###
