"""change_ai_usage_file_name_to_text

Revision ID: dce038d69129
Revises: add_system_settings
Create Date: 2026-01-15 15:48:20.756330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce038d69129'
down_revision: Union[str, None] = 'add_system_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_usage_logs', 'file_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('system_settings_key_key', 'system_settings', type_='unique')
    op.drop_index('ix_system_settings_key', table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=False)
    op.create_unique_constraint('system_settings_key_key', 'system_settings', ['key'])
    op.alter_column('ai_usage_logs', 'file_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
